## Project Goals

The aim of our project is to develop a package called "BDegreeAdvisor" that helps Brown Students navigate the different concentration requirements, semester schedules, and career opportunities.

## Why is this important

Throughout our time at Brown, we have struggled to navigate Brown's online resources to design an education plan that allows us to meet all our concentration requirements but also to explore Brown's Open Curriculum. Often times, we have multiple tabs open to compare different concentration requirements and available courses of interest. Especially, when we were freshmen, we found that navigating Brown's curriculum was overwhelming and confusing. We believe that our package will not only help students to thoughtfully design their academic plans, but also provide resources to faculty and peer advisors to support students. Additionally, our package will expand the career options for seniors and graduate students, who often wrestle with their plans after graduation.

## Project Details

This project is split up into four sections:

    1. Compile concentration requirements and semesters in which these courses are available into an easy-to-read table by webscrapping Brown University concentration websites
    2. Create a table that compares the courses that are required in two concentrations and the total number of requirements for each one.
    3. Put together a schedule of available required courses by comparing the concentration requirements with the courses available in any particular semester.
    4. Use a job search website to develop a table that includes job opportunities by location, salary, job title and description, etc.

## Steps and tools

    1. We will use the devtools package to develop a package by providing R functions to complete our proposed objectives. We will have the following functions:
    - conc.req: This function will webscrape a table from Brown University concentration websites. The input will be the concentration name. The function will first search for the input concentration in the Focal Point website ("https://bulletin.brown.edu/the-college/concentrations/") and select the link that redirects the user to the list of the concentration requirements. The outputs will be the table of requirements and the link to the department page.
    - conc.comparison: This function will compare two concentrations by returning a table of the courses that are required in both concentrations and the total number of requirements for each concentration. The input will be the two concentration names and the output will be this table.
    - sch.req: This function will help students plan their schedules by comparing concentration requirements and course offerings in a particular semester. We will use R as a browser to navigate the Courses at Brown website (https://cab.brown.edu). The inputs will be the concentration name and the semester of interest (Fall Year or Spring Year). The output will be a table with a mock schedule of the courses offered that semester.
    - career.search: This function will use R as a browser to use a job search engine (Glassdoor.com, Indeed.com, or Monster.com) to explore different job positions, salaries, location, title, description, etc. The input will be dependent on the website we choose and the output will be a table that includes all the previously mentioned features.
    2. We will use the package metadata to populate the description file of our package.
    3. We will use the roxygen2 package to create the documentation for our package.
    4. We might consider using the package "testthat" to make sure the package works properly. We will also use mock data for testing.
    
## Task Assignment

    conc.req: Carolina
    conc.comparison: All
    sch.req: Weiqi
    career.search: Joyce