---
title: "Shiny App Proposal"
output: html_document
---

# Overview

The app will be an interactive interface for users to explore concentrations and their requirements to assist them in academic planning. Graphical and statistical output will provide comparative information and help users plan their semesters accordingly. Users will be able to select concentration(s) and a semester from pull-down menus to get the information they need.

# Why this is important

Throughout our time at Brown, we have struggled to navigate Brown's online resources to design an education plan that allows us to meet all our concentration requirements but also to explore Brown's Open Curriculum. Often times, we have multiple tabs open to compare different concentration requirements and available courses of interest. Especially, when we were freshmen, we found that navigating Brown's curriculum was overwhelming and confusing. We believe that our package will not only help students to thoughtfully design their academic plans, but also provide resources to faculty and peer advisors to support students. Additionally, our package will expand the career options for seniors and graduate students, who often wrestle with their plans after graduation.

# Components

Users will be able to select a concentration and get a table of the required courses for the selected concentration. They will also be able to select a second concentration and compare requirements between the two concentrations. They will be able to plan their semesters by choosing a concentration and semester and view which of their required courses are being taught in the selected semester. Additionally, users will be able to explore concentrations by selecting a concentration and viewing data visualizations about historical concentration demographics.

